language: rust

rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src

script:
  - cargo build --verbose
  - cd test_project/test-crate3
  - cargo build
  - cd ../..
  - cargo test
